# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('sshcomm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_password',
            field=models.CharField(max_length=40, verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
