# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('sshcomm', '0002_auto_20170118_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_password',
            field=models.CharField(max_length=128, verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
