# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
